server:
  port: 8099

influxDb:
  url: ${INFLUXDB_URL:}
  organisation: ${INFLUXDB_ORG:}
  bucket: ${INFLUXDB_BUCKET:}
  token: ${INFLUXDB_TOKEN:}

configuration:
  uploadDirectory: ${UPLOAD_DIRECTORY:}
  title: ${TITLE_APPLICATION:Le Lab Sigma - Mangeoires connectées}
