server:
  port: 8099

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/birdy}
    username: ${POSTGRES_USERNAME:my-user}
    password: ${POSTGRES_PASSWORD:my-password}
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

influxDb:
  url: ${INFLUXDB_URL:}
  organisation: ${INFLUXDB_ORG:}
  bucket: ${INFLUXDB_BUCKET:}
  token: ${INFLUXDB_TOKEN:}

configuration:
  uploadDirectory: ${UPLOAD_DIRECTORY:}
  title: ${TITLE_APPLICATION:Le Lab Sigma - Mangeoires connectées}
